version: '3.8'
services:
  nestjs_api_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEST_API_PORT=${NEST_API_PORT}
      - NEST_API_BASE_URL=${NEST_API_BASE_URL}
      - FRONT_END_PORT=${FRONT_END_PORT}
      - FRONT_END_BASE_URL=${FRONT_END_BASE_URL}
      - MYSQL_CONTAINER_NAME=${MYSQL_CONTAINER_NAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
      - STEAM_API_KEY=${STEAM_API_KEY}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - ACCESS_EXPIRE_TIME=${ACCESS_EXPIRE_TIME}
      - REFRESH_EXPIRE_TIME=${REFRESH_EXPIRE_TIME}
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    networks:
      - nestjs_networks

  mysql:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
      - MYSQL_TCP_PORT=3306
    networks:
      - nestjs_networks
    volumes:
      - ./mysql_data:/var/lib/mysql
networks:
  nestjs_networks:
    driver: bridge

    