version: '3'
services:
  nestjs_api:
    image: gjeodnd12165/steam_todo:latest
    platform: linux/amd64
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - MYSQL_CONTAINER_NAME=${MYSQL_CONTAINER_NAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
      - STEAM_API_KEY=${STEAM_API_KEY}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - ACCESS_EXPIRE_TIME=${ACCESS_EXPIRE_TIME}
      - REFRESH_EXPIRE_TIME=${REFRESH_EXPIRE_TIME}
      - NEST_API_BASE_URL=${NEST_API_BASE_URL}
      - FRONT_END_PORT=${FRONT_END_PORT}
      - FRONT_END_BASE_URL=${FRONT_END_BASE_URL}
