services:
  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    ports:
      - '${NEST_API_PORT}:${NEST_API_PORT}'
    volumes:
      - ./src:/usr/src/app/src
  mysql:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
      - MYSQL_TCP_PORT=3306
    volumes:
      - ./mysql_data:/var/lib/mysql
