services:
  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '7777:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - MYSQL_CONTAINER_NAME=${MYSQL_CONTAINER_NAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
      - MYSQL_TCP_PORT=${MYSQL_TCP_PORT}
      - STEAM_API_KEY=${STEAM_API_KEY}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - ACCESS_EXPIRE_TIME=${ACCESS_EXPIRE_TIME}
      - REFRESH_EXPIRE_TIME=${REFRESH_EXPIRE_TIME}
      - BACK_END_URL=${BACK_END_URL}
      - FRONT_END_URL=${FRONT_END_URL}
    volumes:
      - ./src:/usr/src/app/src
  mysql:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql
    restart: always
    ports:
      - '${MYSQL_TCP_PORT}:${MYSQL_TCP_PORT}'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
      - MYSQL_TCP_PORT=${MYSQL_TCP_PORT}
    volumes:
      - ./mysql_data:/var/lib/mysql
