version: '3'
services:
  nestjs_api:
    image: gjeodnd12165/steam-todo:latest
    platform: linux/amd64
    ports:
      - '80:3000'
    command: >
      sh -c "
        echo 'Environment variables:' &&
        echo 'NODE_ENV: '$NODE_ENV &&
        echo 'MYSQL_CONTAINER_NAME: '$MYSQL_CONTAINER_NAME &&
        echo 'MYSQL_DATABASE: '$MYSQL_DATABASE &&
        echo 'MYSQL_USER: '$MYSQL_USER &&
        echo 'STEAM_API_KEY: '$STEAM_API_KEY &&
        echo 'BACK_END_URL: '$BACK_END_URL &&
        echo 'FRONT_END_URL: '$FRONT_END_URL &&
        exec node dist/main"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MYSQL_CONTAINER_NAME=${MYSQL_CONTAINER_NAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
      - MYSQL_TCP_PORT=${MYSQL_TCP_PORT}
      - STEAM_API_KEY=${STEAM_API_KEY}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - ACCESS_EXPIRE_TIME=${ACCESS_EXPIRE_TIME}
      - REFRESH_EXPIRE_TIME=${REFRESH_EXPIRE_TIME}
      - BACK_END_URL=${BACK_END_URL}
      - FRONT_END_URL=${FRONT_END_URL}