name: Docker Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v6.3.0
      with:
        context: .
        push: true
        tags: gjeodnd12165/steam-todo:lts-alpine
    
    - name: Install jq
      run: sudo apt-get install jq -y

    - name: Generate .ebextensions config
      run: |
        mkdir -p .ebextensions
        echo "option_settings:" > .ebextensions/env.config
        echo "  aws:elasticbeanstalk:application:environment:" >> .ebextensions/env.config
        echo '${{ toJson(secrets) }}' | jq 'to_entries | 
          map(select(.key | 
            test("^(AWS|DOCKERHUB)") | not)) | 
          from_entries' |
        jq -r 'to_entries[] | "    \(.key): \"\(.value)\""' >> .ebextensions/env.config
        echo "    ENVIRONMENT: \"${{ vars.ENVIRONMENT }}\"" >> .ebextensions/env.config

    - name: Create deployment package
      run: |
        zip -r deploy.zip .ebextensions docker-compose.yml
    
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        version_label: ${{ github.sha }}
        application_name: steam-todo
        environment_name: steam-todo-env
        region: ap-northeast-2
        deployment_package: deploy.zip